import = ["/home/whoami/.config/alacritty/themes/themes/ayu_dark.toml", "/home/whoami/.config/alacritty/fonts.toml"]
live_config_reload = true
# "window.opacity" = 1.0

[cursor]
unfocused_hollow = false
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.5
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 1.0
# Override "block" cursor if you don't like how it looks in this fork
# I prefer "underline"
block_replace_shape = "underline"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
# history = 10000
# multiplier = 3
startup_mode = "Windowed"
opacity = 1.0

[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 15
y = 15
